title: Distant Lands
description: Distant Lands System Reference Document (v.1.0)
theme: just-the-docs
color_scheme: light
plugins:
  - jekyll-sitemap

url: https://just-the-docs.github.io
markdown: kramdown
